### ISSUE TITLE
kazefuri.me safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#417] opened 2019-08-31 17:00 UTC
Example link : 
http://kazefuri.me/?id=MnU1YzVFdGMvWFJLZ0VWUTJzdDFWZ0hsYXhQZlRwVGtORGtXV3Q4WHh0MD0=
http://kazefuri.me/?id=MnU1YzVFdGMvWFJLZ0VWUTJzdDFWbERURlNTZGYzdk5NaW1mQno3OXk1UT0=

Source link : 
`https://kazefuri.web.id/the-kings-avatar-2019-episode-38-subtitle-indonesia/`

**Comment by timmyRS** [comment] 2019-09-01 11:28
Duplicate of #193

**Closed by timmyRS** 2019-09-01 11:28 UTC
