### ISSUE TITLE
request: pastelinku.net

### ISSUE THREAD

**Issue by adammalyck** [timmyRS/Universal-Bypass#643] opened 2019-11-23 11:13 UTC
http://pastelinku.net/?id=QWM0WElDRFlwcVgyVU5zdXBvaHJ2MU51UEowdmdqd2VLRkdzWEZERS9iL0JFUVpTbU9HRlIrMGdGWXlYU2hvVTNHeklBTTNMbGtaRjBiVy93VzMxM3BXV0VxSXNqL1VWL0FENmhrMGo3Nzg9

source :
https://drivenime.com/detective-conan-movie-23-the-fist-of-blue-sapphire-subtitle-indonesia/

**Comment by timmyRS** [comment] 2019-11-23 11:20
Duplicate of #193

**Closed by timmyRS** 2019-11-23 11:20 UTC
