### ISSUE TITLE
landscapenature.pw safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#407] opened 2019-08-29 21:04 UTC
Example link :
http://landscapenature.pw/?id=OG0wWnJ5MWlFbDJsYXVKekVURDFaMU1ucDMxbGNGemFialc0bkFLUGw2NFIwd3doQy9YOXUzTEF2RkJRSks1eGgvNDU1OFh5Q3FnZVh5V0tpbXJJYTJCRFA5YWNHWnI2aGJON2dzVHlMbzg9
http://landscapenature.pw/?id=T1p3S3pVRWRQZ1JRblY1VWJ3VFJxcjVvOGloWTYyOThTbGdReGtWZXhZYz0=

Source link : 
`http://gantzid.com/jojos-bizarre-adventure-golden-wind/`

**Comment by timmyRS** [comment] 2019-09-01 10:44
Duplicate of #193

**Closed by timmyRS** 2019-09-01 10:44 UTC
