### ISSUE TITLE
This link fixed the bypasser

### ISSUE THREAD

**Issue by jhin08** [timmyRS/Universal-Bypass#935] opened 2020-02-15 00:10 UTC
https://linkvertise.com/20540/proxokeyy

**Comment by timmyRS** [comment] 2020-02-15 00:24
Seems to be working fine for me.

**Comment by jhin08** [comment] 2020-02-15 00:46
wait ill show you

**Comment by jhin08** [comment] 2020-02-15 00:48
[image: image.png]

**Comment by timmyRS** [comment] 2020-02-15 01:31
That image did not come through.

**Comment by jhin08** [comment] 2020-02-15 01:37
https://mail.google.com/mail/u/0?ui=2&ik=2716b39ee4&attid=0.1&permmsgid=msg-a:r2934824314968687048&th=17046510c3092867&view=fimg&sz=s0-l75-ft&attbid=ANGjdJ_N00O68QN6pvXQ7hFxqObEA6SUaiaeQuHx04TGqcC4h5qE8xDZqY9XNdPLOGg_bCXjZunvm9KIdieBMsczAdGph0z0UCgqzRHGAGr2Nef_al5b_f6PA6WaK-I&disp=emb&realattid=ii_k6mvt6yn0

**Comment by KagaKouko99** [comment] 2020-02-15 01:46
in the second linkvertise. they detect if there is a bypass directly. so it can be tricked by the 20 second timer in option "Take me to destinations after x second (s) option. (Use 0 to be navigated instantly.)"
![Annotation 2020-02-15 084322](https://user-images.githubusercontent.com/54178411/74579725-60423e00-4fcf-11ea-97b6-be694151462d.png)

**Comment by jhin08** [comment] 2020-02-15 01:47
is this
[image: image.png]

**Comment by timmyRS** [comment] 2020-02-15 11:20
I have waited 20 seconds before clicking the link in this message and it worked:
![image](https://user-images.githubusercontent.com/11009697/74586968-75c66080-4fed-11ea-9e8c-d5ccf3d96930.png)
I might add some sort of message to that page, to indicate that it would be unsafe to navigate to early.

**Comment by KagaKouko99** [comment] 2020-02-15 11:37
yeah and the last linkvertise also detect if someone navigated instantly. 


![Annotation 2020-02-15 183448](https://user-images.githubusercontent.com/54178411/74587181-0dde3d00-5022-11ea-9492-f2b87ddf26cc.png)
at least wait 10 to 15 seconds to get through it.

**Comment by timmyRS** [comment] 2020-02-15 11:58
This will be fixed in 13.2.

**Closed** 2020-02-15 11:58 UTC

**Comment by ghajini** [comment] 2020-02-23 06:08
`https://linkvertise.com/72834/M00nfrmatn`

Setup= firefox android stable, universal bypass,ublock origin

Issue=
While bypassing `https://linkvertise.com/72834/M00nfrmatn`
Target location tab is quickly closed in firefox android

**Comment by timmyRS** [comment] 2020-02-23 06:31
Works fine for me on Firefox for Android using UB 13.4.

**Comment by ghajini** [comment] 2020-02-23 06:39
I checked only with universal bypass 13.4,
Tab(pastelink.net) is closed automatically

**Comment by timmyRS** [comment] 2020-02-23 06:41
Not by Universal Bypass.

**Comment by ghajini** [comment] 2020-02-23 06:42
I checked with all other extensions disabled, only UB13.4 was active

**Comment by timmyRS** [comment] 2020-02-23 06:50
Can't reproduce.
