### ISSUE TITLE
request: go.x-forex.site

### ISSUE THREAD

**Issue by adammalyck** [timmyRS/Universal-Bypass#617] opened 2019-11-23 01:26 UTC
https://go.x-forex.site/?id=Q1NSbWVkeGVCU0FnK2ZmYStEWWN3VnBsODJ0QlBKdVFZazkzckZkS3hLRFhBM2h1TmNOODZSUCtRSHNZQXBJZk1yZkZjTjdyd3ZJRS82MFFFZ1Vsdm9GdEJvU2lVM2JqSERMZWkzWjVBRTJaNjA4WmZjUllDeFhLQTZjSVJ1VmkyWUNRU0x3SmUxYVRyRHNEN3kvSk93PT0=

**Comment by timmyRS** [comment] 2019-11-23 02:14
Duplicate of #193

**Closed by timmyRS** 2019-11-23 02:14 UTC
