### ISSUE TITLE
request: landscapenature.pw

### ISSUE THREAD

**Issue by adammalyck** [timmyRS/Universal-Bypass#639] opened 2019-11-23 10:41 UTC
http://landscapenature.pw/?id=OW1KTkZBUE10UmJjeXE2citBUG1WamJkeEk1QVNjdTRYbDF1c0ozUDNkUkdGM0JmODJUU21QaHNuakFkaUFYSEtzVWYyOVZkVFdiK0QyK0lJZ1Z4ZVE9PQ==

**Comment by timmyRS** [comment] 2019-11-23 10:42
Duplicate of #193

**Closed by timmyRS** 2019-11-23 10:42 UTC
