### ISSUE TITLE
[Request] lifesurance.info

### ISSUE THREAD

**Issue by falfan2018** [timmyrs/Universal-Bypass#253] opened 2019-06-02 15:57 UTC
http://lifesurance.info/?id=K3cvb3VPVzJkSnhSZWhwejRhdkZING1QcjJSTWlNdHliSDVMNFY3RHE0cHhtRFhiNHdRcE9Bc20zY1Q5MktKOEQ1V0dpVzN3M2NaZGVyYW1tU0dWazJaWGZldWVra0ZMTy9pcEhaYzZjRUNobEx4dVl1NGxxVnl2WkpkUGYvalM=
http://lifesurance.info/?id=YWRRVGV6YWlzWmRrNjUxeU14ZkszWmprcGpTSzVPbGVnRmt6N1BYb2FzNC9oU3p1ZWYvN1d5S2doQmdEVGJuSGxxTnNPWTFjZlZlTnNGQkt3SnNSNEE9PQ==
http://lifesurance.info/?id=TjdZWVc3Vy9Ca2lnRUw5ZEtQWkNWcmdiL1pmMjRIOTFyMXU0T0ZiRnpzb2lxZjdKSmRGeTdqSlRUMVplczZUUlpRZ05oQ3JHNDBLeFhvbU15YWFFdFE9PQ==
http://lifesurance.info/?id=eUVSVm5UbEtHbTYvYXZhUU0vNlQ2QzIrQXVpZnRkZmxCakh3ajM2S0FUWExPcUh5bEZlRFY0N0FVYnU0MmhDZQ==

**Comment by timmyrs** [comment] 2019-06-03 08:48
Duplicate of #193.

**Closed by timmyrs** 2019-06-03 08:48 UTC
