### ISSUE TITLE
Req bermedsos.com

### ISSUE THREAD

**Issue by falfan2018** [timmyRS/Universal-Bypass#364] opened 2019-08-18 07:17 UTC
http://bermedsos.com/?id=SFVkQ3pPWUt1ektOTUNDMFRYWk80RmJ3Z05QeVhBRS95ejZlTnN2VThySVlzUFJqaC9LcEV4bjhVUVdISXIycHdJQ2d5QXVrOFI2NExKZDltdzVQd0xSVkNQZjBpK2VDem9ZbFhSVG5JeTlOSFNnYlk0Z1dJaitVVmxnOWQxWkhhQy9yNG0yQzVnNlVlS0RTa3ZXU0cvM0lmVjIvTXNZS21WQTFMK0tVa2p3RFdINHVJamJZTVJ5RHhDaFdsaDNyektBWUVQUmNtZUV3S2Yxb1lVZnNRQT09
http://bermedsos.com/?id=SFVkQ3pPWUt1ektOTUNDMFRYWk80UDVpc0ZsTkxhZ1d5d2xGS3Y5SnMrdC84ZGlkQ1hnTG4zSTAycUgxaDRKYmFjYVB5YTlaNFBTWFZjaVo1dythRkttSGY1cGJuT0ZVdEZKVmRxRXFUN3FuczhqOW5QS0ZXeVFXUXdJV2tCSTNXRWVwOFJNVS9lOXR5V2JIN21HM2tmc3EzQXkvN2ZiZU1kTldDOGtFMTcyRkFDbm4reGVJYXBqRGpUZnBLL2I5MXJBSWFiK09GNEFBT05EZEdXQUo4UT09
http://bermedsos.com/?id=SFVkQ3pPWUt1ektOTUNDMFRYWk80S2Znazd2Zk9GdThJQkZsZ1pYd214U3FjVVU2TFZtVEpZTmxaNjU2UjY3QXpIRFJFUmpIRFdZbnB6dDNNMlBrdk13QlJyYWMyREdKTFMzZitLNEhkaHYyUlIwT1k2eUZoT0RaTU5xK1JrT2pUS3dEaDNMLzE5TkppQ2pqTk1YV3JObGg2L0dnZkl2ZHFZWmVReVdDZUVNTnljN1dvQ3VnWjRoZ2JHK3dKenlqemJDekNVaGFCVnVsTXhPVm0yL3laUT09
http://bermedsos.com/?id=SFVkQ3pPWUt1ektOTUNDMFRYWk80TTRNOHBUMHR5dDhuMVdObTZ2YmJYQTdXVHc4QTRmeEVTNVZyK3VzK21hckhWdDJRQ09aK2FuRk4wdGtGS3FyTEg2eVM2Z3ZvMlU5cnIzQkNnVXh0MEZXYzc2V1VkQjhUN2JHZWtQRGQzNXF2c3BXYWYrQU1jY3ZKVHIwWDBqd3dPQjV3cUxsaFR0R1FDcm1Jb3I5Wmxtdzd3ZmFyMkdyZkhuWElwTWNWaGFBWlduaEVSdGRVN0VCdFhIRU81M2VSdz09

**Comment by timmyRS** [comment] 2019-08-19 15:47
Duplicate of #193

**Closed** 2019-08-26 20:53 UTC
