### ISSUE TITLE
ironimesafelink.my.id safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#475] opened 2019-09-25 03:26 UTC
Example link : 
http://ironimesafelink.my.id/?id=Sm9LamwzQldVU2YwamNPTVcrYU5SMkJnQUFJYlRVdzJHTWt0aVc2eVBFWT0=

http://ironimesafelink.my.id/?id=c1dtN1EvNERtSndZS3BPdG44NE5UcUhzODh1WkhPbW95cEJHV3lIWHU5ND0=

Source link : 
`https://kazefuri.web.id/pokemon-sunmoon-episode-102-subtitle-indonesia/`

**Comment by timmyRS** [comment] 2019-09-25 05:36
Duplicate of #193

**Closed by timmyRS** 2019-09-25 05:36 UTC
