### ISSUE TITLE
please add travellinginfos.com and kontenajaib.xyz

### ISSUE THREAD

**Issue by Arsindy** [timmyRS/Universal-Bypass#882] opened 2020-01-28 15:20 UTC
sample https://kontenajaib.xyz/?id=YlI3bmpMeS9uc1QwTFJTTjcrY3lMcVhKSC9ObGR4ajIyaUwxSk94QnlhbHB2enQzQ1JENkN6eERIMVorcng5STN2V29IbDVSZ0RTVUZqQmU3eXE2TlE1SFRrVjJXWWZDRFQxMHYwdDQxeU43VjRxRk8xUDNHMHZOeHBzUlVyZXVDYVlDRGJxZVRrVEVXM1BnRDdRWE5NY1pGWjRxVDIvbGtFeVBXK1dYWS9WelhEV1BBeWlyUXB4cGJha1BFZWVtdXBocVFOTnR5dHRjYzBJU1haM2luclBKVFdPQ3pPOHlVbGVIQ3l2RmZZdHFtMlY5MTh1WjVTK29NUFRiM3EyZg==

this link comes from https://www.oploverz.in/black-clover-episode-119-subtitle-indonesia/

**Comment by timmyRS** [comment] 2020-01-28 15:24
Duplicate of #807

**Closed by timmyRS** 2020-01-28 15:24 UTC
Labels: new bypass
