### ISSUE TITLE
linkach.com safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#404] opened 2019-08-29 19:37 UTC
Example link : 
http://linkach.com/?id=NEI5dCt1SWVNNC9uM01OUEFka004Z0twRmlYbkFFaTdiQVhqcVZZcENBYXFnNlhiNSs4RUczU2M4Y3BLalQ1TQ==
http://linkach.com/?id=Y3puclVLdGRzMTlRV3BuVC9EVE1UM2NDMjc1QmNvZFZkaGk1Qml6dlNEb05RbXdUb0xGenlWQ2NGMU5XajUxZmNFUTRyMVlzdVBoR3VjU3RtcDE4VlAxQldQbHNCcENZczhLeEQ3dVgxaWgrTzVnc1IzR0RSMlArdHNna1dhZFBrM05udE9LL3VJUzFhK1RpS1pSaGlRPT0=

Source link : 
`https://www.achanime.net/spira-spica-iya-yo-iya-yo-mo-suki-ni-uchi-single/`

**Comment by timmyRS** [comment] 2019-09-01 10:43
Duplicate of #193

**Closed** 2019-09-02 14:01 UTC
