### ISSUE TITLE
Request sehatsegar.net

### ISSUE THREAD

**Issue by falfan2018** [timmyrs/Universal-Bypass#266] opened 2019-06-10 19:49 UTC
http://sehatsegar.net/?id=QW03bzhWS1N6K2xUbEQwL1g2WFhiNk1va2RvTzdna282dUZyMDR2SThpa0RzbG5hTDE5dGJzUHpTUUlZRUk1a2Z4dGRwQjhiZEM3ODFYMzVZVmp2MVVOY3ZhYXZMRWVwcHVIVko1Z1VlcVk9
http://sehatsegar.net/?id=QW03bzhWS1N6K2xUbEQwL1g2WFhiNk1va2RvTzdna282dUZyMDR2SThpbllPaGZFNCt5Tng1dlhsck8rL0h1M1RPU0pZUEpqMHBsanVQSDRtbnJBS05jWjBFekJ2bXpwS3hha1JWYVc0WW89
http://sehatsegar.net/?id=YU5UMUg1alFNZWZOTktFc1gvdXdlU3ZsRlNCYkhWaU50RUhvTi9kZXF3ZnNKbHFBKytzOWx5NjhaRnY4bjVoRTZWcDdBSklyWlRheDc5ckpYS21SUEJTbllJR0kzSnNFeHUvbU11dUZCZjQ9
http://sehatsegar.net/?id=ZzNJL1JPQ2hZZzREQVc1d1VIVjRuWmxwbXowR0FPSU9yajMvaDhYWHA3QU1vU1pTdDlHT1BJMVRUTDFQYWprUA==

**Comment by timmyrs** [comment] 2019-06-10 22:20
Duplicate of #193.

**Closed by timmyrs** 2019-06-10 22:20 UTC
