### ISSUE TITLE
Request travellinginfos.com

### ISSUE THREAD

**Issue by WaferNabati** [timmyRS/Universal-Bypass#508] opened 2019-10-11 18:36 UTC
https://travellinginfos.com/?id=a3lFT1dFU2gvRHhRdFJWRnRGZ3k5UUllaktvQ2N5ajNVcEVSbEdQQlNHazVudkxhMExwZWIrY2tveU5oYXRqcENONmxoMDRsMWdOaWh5ZERwbUh2TUE9PQ==

https://travellinginfos.com/?id=V3A1c1RHVlh1eDZnYmJPeExGc0VRREc5b1NJUTdoNnFvZ1JlRVdMVmJ1QXlObE1NUWYyZDNLRE1BSllzL2ZJWE1jeFNoM2YyS1lBUEFQRExObUlYa1E9PQ==

**Comment by timmyRS** [comment] 2019-10-12 10:26
Duplicate of #193

**Closed by timmyRS** 2019-10-12 10:26 UTC
