### ISSUE TITLE
kontenajaib.xyz safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#582] opened 2019-11-19 16:25 UTC
Example link :

https://kontenajaib.xyz/?id=TXZXdjVHb3p2Q0pmb3IwdGlVZEczSlZJTHBtTUNuNU0vQ0hYejBvT1lUOD0=
https://kontenajaib.xyz/?id=TXZXdjVHb3p2Q0pmb3IwdGlVZEczTXhFTyt4THQxVDhMeHJvS1l5K05IWT0=

Source link : 
`https://www.oploverz.in/black-clover-episode-110-subtitle-indonesia/`

**Comment by timmyRS** [comment] 2019-11-19 18:47
Duplicate of #193

**Closed by timmyRS** 2019-11-19 18:47 UTC
