### ISSUE TITLE
zona-aman21.com safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#480] opened 2019-09-28 17:13 UTC
Example link : 
https://zona-aman21.com/?id=WGhDQ3N2RTRPOHF0eDFmc3lnRHhGTGwvWXB0ZHp1VXk3N0h5Vis2Q1NWSElscVhndlc5b05KOHJ1T1dxNjJGbGtsbXNTdzlXV2xwcUlZNGpUVlczU1lNUHpQTXJ0QStMcXl4UVdCYUtzS0E9

https://zona-aman21.com/?id=WGhDQ3N2RTRPOHF0eDFmc3lnRHhGTGwvWXB0ZHp1VXk3N0h5Vis2Q1NWRUh4Ukl0NzRWcUlhSHZNaE5Pc0J5OGxmVTYzNkg2M1IwR05ick9iWWExeVRjTUUzOWZhRFRIQkpseVF0clNYV1E9

Source link : 
`https://wibudesu.com/dungeon-ni-deai-wo-motomeru-no-wa-machigatteiru-darou-ka-ii-subtitle-indonesia/`

**Comment by timmyRS** [comment] 2019-09-29 11:47
Duplicate of #193

**Closed by timmyRS** 2019-09-29 11:47 UTC
