### ISSUE TITLE
Request desusafe.info

### ISSUE THREAD

**Issue by WaferNabati** [timmyRS/Universal-Bypass#488] opened 2019-10-03 13:25 UTC
http://desusafe.info/?id=dXNYRDZZQUZSVGFORUlKVCtmSG83WWhpK1p2ZTg1RTF4T25sdWZ3cEpvYVNPYm9CdUxrQ2ptNmR4RktlUXk0Q3pwS1pRWE9lNU9RYjUyUVl2RVpvb1E9PQ==

http://desusafe.info/?id=UEZGQ2FBdDUrNXF6R1QyMG4rRnN0M1RETFlnZnBjQXM3WHF6Qzd2aytaUT0=

Source : 
`http://otakudesu.org/rdnt-s2-episode-1-sub-indo/`

**Comment by timmyRS** [comment] 2019-10-03 21:21
Duplicate of #193

**Closed by timmyRS** 2019-10-03 21:21 UTC
