### ISSUE TITLE
Req Bypass https://kontenajaib.xyz/ and https://travellinginfos.com/

### ISSUE THREAD

**Issue by Username778** [timmyRS/Universal-Bypass#585] opened 2019-11-21 06:24 UTC
Sample link

https://kontenajaib.xyz/?id=TGp1VkxRYlR0TnFnc1VvWm5xODZxVGtENXFNQmFDUEpyNzJVWU1nTkZkYVVqUmM1S21McGJ5UXFjSG43dEE3TUlSZE9SdG5kcUt2U3BScEdqOHQrQnhjY2IzVVdUUnpwVWR6eFFhR2tlYkZJY0NlVEttenpBamV4aDR5KzhXU1N4QWN4eXFvdUZra3BRVlhUblRwNXMvTVNVNGdQWWtwenJjRXhiREFWdEJyYU95T1M2dGRwelcwWXNwRjFod1ZxMjVVTnc1TzJpUHd3dnVzdjJjQU9WRXJGbkdMRkVKeFM3Y3NTNkIvTEEvNWtwYkJDbjY0dFpQdytvZnB1MGF4cnFESHlyZVRvd0p5MVA4TjNWZi9JZkpJeFA0MkExS3Zybk1RUlQ4U3hDbU1Uai81VVZqcnIxUWNJeTVmZU1lYTk=

https://travellinginfos.com/?id=TXZXdjVHb3p2Q0pmb3IwdGlVZEczR3BQQ2hnVlJYaFgwNTh0VC9iUVhlOD0=

**Comment by timmyRS** [comment] 2019-11-21 06:25
Duplicate of #193

**Closed by timmyRS** 2019-11-21 06:25 UTC

**Comment by its4win** [comment] 2020-01-03 06:22
https://github.com/timmyRS/Universal-Bypass/issues/193#issuecomment-570475925
