### ISSUE TITLE
Bug kurosafe

### ISSUE THREAD

**Issue by falfan2018** [timmyrs/Universal-Bypass#224] opened 2019-05-13 19:22 UTC
Example link :
https://kurosafety.menantisenja.com/?lanjut=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL29wZW4/aWQ9MW1Xb0FYWGU0Ujd1cVlMY3VudGpGM2Ixa19IR2c0d1lX
https://pafpaf.info/?kuy=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL29wZW4/aWQ9MW1Xb0FYWGU0Ujd1cVlMY3VudGpGM2Ixa19IR2c0d1lX

`https://www.kurogaze.me/dororo-episode-18-subtitle-indonesia/`

**Comment by hjyoung1** [comment] 2019-05-13 20:07
Looks duplicate of
https://github.com/timmyrs/Universal-Bypass/issues/193

**Closed** 2019-05-13 20:10 UTC
