### ISSUE TITLE
linkvertise.com is not bypassing

### ISSUE THREAD

**Issue by XxSeBasti4nxX** [timmyRS/Universal-Bypass#700] opened 2019-12-11 18:05 UTC
please help me. it is not bypassing linkvertise.com. can you fix it please?

**Comment by jdearaujo1** [comment] 2019-12-11 19:31
Issue was already reported, I think he'll fix soon

**Comment by XxSeBasti4nxX** [comment] 2019-12-11 19:33
okay

**Comment by timmyRS** [comment] 2019-12-11 22:02
Duplicate of #695

**Closed by timmyRS** 2019-12-11 22:02 UTC
Labels: broken bypass
