### ISSUE TITLE
request: sweetlantern.com

### ISSUE THREAD

**Issue by adammalyck** [timmyRS/Universal-Bypass#620] opened 2019-11-23 01:43 UTC
https://sweetlantern.com/?id=dC94MXMvbTRkK21jV1doNE1ZdWMzYlNWWE5sMUN3aElxcFRWNkN2enp3RT0=

**Comment by timmyRS** [comment] 2019-11-23 02:13
Duplicate of #193

**Closed by timmyRS** 2019-11-23 02:13 UTC
