### ISSUE TITLE
apasih.pw safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#406] opened 2019-08-29 21:01 UTC
Example link : 
http://apasih.pw/?id=a1NobVhjdlBzd2lucDN3OTN0V2l5dUJ5UlVaUzNFZ1V2Zk9NODNtS3JzTGpMY3lXa1FQOXhubU9SZHBoQzYwM0NiUVMvU0d0czNtWmhtR1Evd0o5cEhjbmhWaDRmVTRDdUc5ZDhUanlnTENOeTJkRXN2K1NwRUN3Sk56L3lHZ2g=
http://apasih.pw/?id=YlRRamlWUzZhcGN4WVB3akliVEE4TFBaTks2SnBXRUh0eFlWR0JlL3l1Y3czTUl0a1NqNDFCUkZLS0t2bmU2cQ==

Source link : 
`https://bakacan.id/dc-batch-sub-indo/`

**Comment by timmyRS** [comment] 2019-09-01 10:44
Duplicate of #193

**Closed by timmyRS** 2019-09-01 10:44 UTC
