### ISSUE TITLE
gudtekno.com safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#589] opened 2019-11-22 05:47 UTC
Example link :
http://gudtekno.com/?id=N3NpTXM4d0VkVzNlUlNLcjYrK2FuRlpzQ1puc01lUXNEVmtuQk80Q05VSnNJN2UzV3d6OXFtZHZZdnA4ajVVQWJRWlptZEFaMU9jSmk5cW1scVNkRnYrY3g0dXI1Q3Z2UG4yRCtwV2tHcVU9

http://gudtekno.com/?id=N3NpTXM4d0VkVzNlUlNLcjYrK2FuRlpzQ1puc01lUXNEVmtuQk80Q05VTFlHV2RkWFZhMTlULytDNDlrV1JxQ0FxV2JTcFJhdHdVVUpDWHhCSkRrMjdjZVpWczIwWFZsUCsyeEU5cG1lUDg9

Source link : 
`https://drivenime.com/detective-conan-movie-22-zero-the-enforcer-subtitle-indonesia/`

**Comment by timmyRS** [comment] 2019-11-22 07:16
Duplicate of #193

**Closed by timmyRS** 2019-11-22 07:16 UTC
