### ISSUE TITLE
kuliahmatematika.my.id safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#514] opened 2019-10-15 06:30 UTC
Example link :
https://kuliahmatematika.my.id/?id1=NL7BNN71NnNoNhNDjM7ONSNCNcNP727INhNJNWNnNZ7o75NvNajANA7wjj7INQj3jxNmNW7o70NgjPNZN5NG7.NpjKNbNn727HNV7QN37uNtNONU7JjTN.7JNR7wN2jG767l9928c81ae1c4c471216a71910f263a4502517449d281cbb611f479b6046455f4jXNuj7N5jqNR7INAjANRjONMNCNsN1NSN1jzjwjbjjNgN5jVNvjAjKNzNmj77Fj_j_NZNfNjNcNXNONsN2NHNnNuNDjhjXNON4&id2=

https://kuliahmatematika.my.id/?id1=71No7HNR7l7QNp74N4NONN7HN.NENO7INiN7NbNCN9Ni79NDNaNfNvNKNq74jxNZNy7vNh727.NajPNvN4N9NwNUNPNC71NJNsN3NjNN7O7QNe70NbNXN37lNzNbNJjLNTN0423639ccf2b1064077641dc8de56161eb647f82e77a70668192e703b7fd245b9N4jnNujWN179Nc7aN9jvN4N2jXNejoNfjTN9jsNd71jjNSjbNwNFjqjENn75jKNxNMN.NfNU7vNYNS7YNIjMjnjVNzNBNGN-j7NzjcNK7vNsN1N.jC7472N1NDjPNujnNpN6NZjxNOjwNGN0jMNSNgjwN5N6joNHjJNU&id2=

Source link : 
`https://pendekarsubs.us/ani-ni-tsukeru-kusuri-wa-nai-season-3-episode-2-subtitle-indonesia/`

**Comment by timmyRS** [comment] 2019-10-15 06:30
Duplicate of #193

**Closed by timmyRS** 2019-10-15 06:30 UTC
