### ISSUE TITLE
Request gomentod.com

### ISSUE THREAD

**Issue by WaferNabati** [timmyRS/Universal-Bypass#451] opened 2019-09-15 16:44 UTC
http://gomentod.com/?id=M1ZPOTd1cUg2TktEd2Q2TkZ2NmhUb2NVdC8xcGREYmlPdkpWMERsT2NVUnlrVmFGWUFlSE5HODh2d2JFTnRFQzMwakJNbnZRYm1TZkc2RVhnOFdnNWczdU1qZWMxeExkeC9kd2plSjJlelpxZzFFUXkwMnd1L2dFZzFvRGE1RmY=

http://gomentod.com/?id=OTFwUkJVVHpYdStldmJjYlN0eTVKUzZpTi9PelNNV3VkVE9XVTdRTFNVbkoyUVJ6YlRSSFRxaUpiYm0zU24wN2dMYmVlOUoxc09TQytXY0NGdTdOaHhZYTBPNWlmNlRKTzgxVHlNbFg3ZEE9

Source : https://www.animebatch.web.id/kimetsu-no-yaiba-subtitle-indonesia-batch-1/

**Comment by timmyRS** [comment] 2019-09-15 22:06
Duplicate of #193

**Closed by timmyRS** 2019-09-15 22:06 UTC
