### ISSUE TITLE
need to be support

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#380] opened 2019-08-24 09:40 UTC
example link : 
`https://sweetlantern.com/?id=dC94MXMvbTRkK21jV1doNE1ZdWMzVk1xb1M4M0psV0VCSU9ZdE1qZUJKaz0=`
`https://lonelymoon.net/?id=dC94MXMvbTRkK21jV1doNE1ZdWMzYUZoMjJpSXdzYTdEblpxK3dscTZ6Zz0=`
`https://intercelestial.com/?id=dC94MXMvbTRkK21jV1doNE1ZdWMzU2x2SkM1SEtsR080YkYrRk1QS0JmYz0=`

source link :
`https://pahe.in/avengers-endgame-2019-uhd-bluray-720p-1080p-1440p/`

**Comment by timmyRS** [comment] 2019-08-27 08:44
Duplicate of #193

**Closed by timmyRS** 2019-08-27 08:44 UTC
