### ISSUE TITLE
https://kontenajaib.xyz/?id=VTJpUlluSUE5UXpmRU1Ja3V0eTl3aTk1Z29abmJ5RkFGUC9mdlEwOHd2emZaSkdUdGQzTG1vQk93cHZuby9yK0FJMGVWajlpT3V6SlM2SnZZeHBCSjJreVB1MkxEUXVET2x5a29xVWpxa1pPUmY3WXJjQWRRZDNxa1NzMVB1SjV1dG5sck9NYjdLTkZGdTUwUllmbFA1STZZZ2oya3QwNGkrR2c2d2Q2WGdJZGdQNGd4czhTTDlJSjZLVkc1Y0hBOW5ZS25qV2JZb0pLZ0FGc1AwTTVGV3Jhek9Ecm5mM1BrU3czK3pVRGhUWmlJcVlUNzF2VG02WWtVT3JOc1FKSQ==ENTER DOMAIN HERE

### ISSUE THREAD

**Issue by skyway34** [timmyRS/Universal-Bypass#907] opened 2020-02-04 15:16 UTC
Before you report a website that isn't bypassed yet, please use the search function to ensure that the site wasn't already reported: https://github.com/timmyRS/Universal-Bypass/issues?utf8=%E2%9C%93&q=ENTER+DOMAIN+HERE

If that is not the case, please **provide an example link.** I need to be able to see what there is to be bypassed, otherwise I can't create a bypass.

**Comment by timmyRS** [comment] 2020-02-05 08:57
Where did you get that link from?

**Comment by ikancupang** [comment] 2020-02-07 01:37
Based on the file name: oploverz - DnA S3 44 [mini] [586C1BC5].mkv 78.9 MB (82736470 bytes)
The source comes from: `https://www.oploverz.in/diamond-no-ace-s3-44-subtitle-indonesia/`

This is already bypassed by crowd bypass.

Duplicate of #807

**Closed by ikancupang** 2020-02-07 01:37 UTC
Labels: awaiting response, new bypass
