### ISSUE TITLE
pashalovarian.com safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#405] opened 2019-08-29 20:39 UTC
Example link :
http://pashalovarian.com/?id=WWkrZjJIVWhzK2tXQmlWTHcweGVJTkdiV2lVdEliRklOTHcxZE5nOHlZYkZ0ZCtOSC9NeHI2WmJKODBETUhWUUljUUw2Ym5UbHQ0MnJXMVpqc05UWWhncUF2eHh2TzgzQi82eVBxNkw3alU9
http://pashalovarian.com/?id=L21zK3NMb1JYclcxNzc3RmZyd3cxcGJZdVhzd3R5RzJYOGY4NkxKbVhHeVVqTDYyUmpVRUJaRE5DQTJobVZ3bA==

Source link :
`https://ruangotaku.id/video/lord-el-melloi-ii-sei-no-jikenbo-rail-zeppelin-grace-note-episode-08-subtitle-indonesia`
`https://animersindo.net/video/sounan-desu-ka-episode-09-subtitle-indonesia/`

**Comment by timmyRS** [comment] 2019-09-01 10:44
Duplicate of #193

**Closed by timmyRS** 2019-09-01 10:44 UTC
