### ISSUE TITLE
Please Bypass This Anti Bypass Plugin

### ISSUE THREAD

**Issue by dedsec404** [timmyrs/Universal-Bypass#287] opened 2019-07-03 05:59 UTC
this website (drivenime.com) uses a plugin that has an anti-bypass feature that provides a unique ID at any time

**api.rurafs.me cannot be accessed directly**

> 1nd Redirect
> https://api.rurafs.me/v2/rurasafe/xxxxxxxxx
> 2nd Redirect
> https://bagilagi.com/?k=xxxxx==
> 3nd Redirect
> https://bagilagi.com/xxxxx/
> 4nd Redirect
> https://api.rurafs.me/v2/rurasafe/xxxxxxxxx
> 5nd Redirect
> https://drive.google.com/file/d/xxxxxxx

oh btw, this is **tempermonkey script** that can bypass (drivenime.com)
https://textuploader.com/1dw4p
hope that you can add this script to **Universal Bypass**

**Comment by timmyrs** [comment] 2019-07-03 17:50
Duplicate of #193

**Closed by timmyrs** 2019-07-03 17:50 UTC
