### ISSUE TITLE
[Request] autoride.pw

### ISSUE THREAD

**Issue by falfan2018** [timmyrs/Universal-Bypass#209] opened 2019-05-07 12:21 UTC
Example Link : https://autoride.pw/?id=OHhGV01pNytBVWdHWkFvT2FDYzRvS1ZUUVNSTVZMaTNuZWtuQXBQeThvdkJXdEhqbXA0MndpTG93VTNsL2IvSA==

**Comment by timmyrs** [comment] 2019-05-07 12:37
Duplicate of #193

**Closed by timmyrs** 2019-05-07 12:37 UTC
