### ISSUE TITLE
[Bug] intercelestial.com

### ISSUE THREAD

**Issue by RaveN0X87** [timmyrs/Universal-Bypass#172] opened 2019-03-18 14:29 UTC
https://intercelestial.com/?k=dEROSDg0cm1Cd2JMQ2tPdHpsazRhL2dJUGhUTUx1Tyt6R3hFdmhPc2tKVT0=

https://pahe.in/aquaman-2018-uhd-imax-bluray-720p-1080p/

![Screenshot_2019-03-18 Uh Oh Something Wrong](https://user-images.githubusercontent.com/39649317/54538747-64cd3380-49c7-11e9-8acc-4646509508b8.png)

**Comment by timmyrs** [comment] 2019-03-18 15:42
Duplicate of #170.

**Closed by timmyrs** 2019-03-18 15:42 UTC
