### ISSUE TITLE
req aidainsurance.pw

### ISSUE THREAD

**Issue by falfan2018** [timmyrs/Universal-Bypass#284] opened 2019-06-27 20:06 UTC
https://aidainsurance.pw/?k=dVJ2L1dSZmJNMkR1UHkwOFhteU5UTGRPcnlCdWdVajdwRk1Tc3NZckpqZz0=

`https://ryuukoi.web.id/anime-spring-2019-batch-subtitle-indonesia/`

**Comment by timmyrs** [comment] 2019-06-28 07:38
Duplicate of #193

**Closed by timmyrs** 2019-06-28 07:38 UTC
