### ISSUE TITLE
Request waifusafe.ooo

### ISSUE THREAD

**Issue by falfan2018** [timmyrs/Universal-Bypass#255] opened 2019-06-03 09:43 UTC
https://waifusafe.ooo/?k=MXZOcXU5bUJCbXEzNFp2NnRPM1lMazViY3NXZmRZdFgvQUxuMHhHVUlWM1locisvdTdQQ0hzUnJYdEgzOXdkUW1uazlMSllKdldDVnJDRXJod0d5N2lTVkIzRW55bjM5T2FLZS9sT2pLc3c9
https://waifusafe.ooo/?k=MXZOcXU5bUJCbXEzNFp2NnRPM1lMazViY3NXZmRZdFgvQUxuMHhHVUlWMVBIRXZvMjVHNjJmb1ZiSWxKbW9sT0E5SG10VGpFNUQzZk1TUTJMNGZDN0RNeDdWdE1nbXc5N0NnNjQwbU92Nm89
https://api.rurafs.me/v2/rurasafe/dVJ2L1dSZmJNMkR1UHkwOFhteU5US2tUeE9Bc3pOSm90djU2RlBTNFJaQT0=?Key=e852fe24-4d29-4976-8159-06277671a1e4

**Comment by timmyrs** [comment] 2019-06-03 09:46
Duplicate of #193.

**Closed by timmyrs** 2019-06-03 09:46 UTC
