### ISSUE TITLE
[Request] Bypass 

### ISSUE THREAD

**Issue by falfan2018** [timmyrs/Universal-Bypass#205] opened 2019-05-05 07:40 UTC
Example Link : https://sweetlantern.com/?id=dC94MXMvbTRkK21jV1doNE1ZdWMzZmZJOXhtZGRjd2hNU0xIMUdSRHRpVT0=

https://intercelestial.com/?id=dC94MXMvbTRkK21jV1doNE1ZdWMzY1V5Mkh5WUExd0RJMlZ1N0ZyeDlXQT0=

From : https://pahe.in/game-of-thrones-season-8/

**Comment by timmyrs** [comment] 2019-05-06 00:31
Duplicate of #193

**Closed by timmyrs** 2019-05-06 00:31 UTC
