### ISSUE TITLE
Bug Kurosafe

### ISSUE THREAD

**Issue by WaferNabati** [timmyRS/Universal-Bypass#500] opened 2019-10-08 10:25 UTC
https://www.menantisenja.com/?id=U25CWXdDQStRSDR1bzl3UXZhdWEvRzJrR3JOQ1dkWWhwTjRlSTgxQzdJVXg1ZU1IcWVpUXlPanQvczRSSkJzUw==

https://www.menantisenja.com/?id=V3o1dThnUUk1L0FBVWN3TVNJdGhOaVRxNVhBK1VrcUlBVm9zTFhEOTRzdWZhcWNFblBJWUo2YXliU3lhSENCdlFmZ3dPdS83YWNtVUJEMFhXVTlkcE9ITlplay91VXdpbXltSHRCOThneUE9

Source :
`https://www.kurogaze.in/psycho-pass-sinners-of-the-system-case-1-tsumi-to-bachi-subtitle-indonesia-bluray/`

**Comment by timmyRS** [comment] 2019-10-08 19:55
Duplicate of #193

**Closed by timmyRS** 2019-10-08 19:55 UTC
