### ISSUE TITLE
plz request

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#354] opened 2019-08-16 13:20 UTC
Example 1 : `https://ceklinku.xyz/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL29wZW4/aWQ9MTYzTUNzTmlBanlXbnZfQVlIUmFTeU05Q293WHQxTzNr`

Example 2 : `https://ceklinku.xyz/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL29wZW4/aWQ9MWU0VE9ZUzZmYXFUT3NzU0N3VVJyM0lBdWtvSGpocUVp`

**Comment by timmyRS** [comment] 2019-08-18 20:00
Duplicate of #193

**Comment by anaklayangan** [comment] 2019-08-21 03:51
I think this is just base64 url
`atob(new URLSearchParams(location.search).get('r'));`

**Closed** 2019-08-21 12:33 UTC
