### ISSUE TITLE
Request wanhealth.me

### ISSUE THREAD

**Issue by WaferNabati** [timmyRS/Universal-Bypass#490] opened 2019-10-03 13:33 UTC
https://www.wanhealth.me/?id=VDFQRFhkSVBJQW8vSzNORmhrdHlHSy81TzVsSUpiTUVDSHpWaGJjakpETm5sYjVDckFiQnBUQTQ4a2FBSmVhN3Bna0E4eHZ0cUw0MW1Ld3NVUGdHaVZxOE9zcmRLWjROaTVTZ0dzWmVvYXc9

https://www.wanhealth.me/?id=bDVsUXBCU1I2c1F4Um02T3hNOEVONkhNZEswUE9LVlVDZEtxL0RaSnBMU0RjT0RVSEZUMmx3WlNtNThObHg4NA==

Source : 
`https://www.animebatch.id/hataage-kemono-michi-episode-1-subtitle-indonesia/`

**Comment by timmyRS** [comment] 2019-10-03 21:21
Duplicate of #193

**Closed by timmyRS** 2019-10-03 21:21 UTC
