### ISSUE TITLE
Req jutek.id

### ISSUE THREAD

**Issue by RaveN0X87** [timmyRS/Universal-Bypass#655] opened 2019-11-24 15:44 UTC
https://jutek.id/?id=OU5VbGhSbEVnNWxmQTQwa1RvNUt4YVBRYTJTUHFMWlU5cEM4MU1HNTN3RmdLL3hpb2lGZThOeHhvTng0b0tWVWVTNFdGclM3dGt4MWU4cXJ3WlhQaEpvRmprMk95YS8vbUZ5dTlqM3Q2SnM9

https://jutek.id/?id=WldjNzBRQ1ZNdko5RzB2K0lHQ1M5L25RNjc5ekc2RXJMemh0dzlBa0JPRDRVK3l5bHljb0F4MGp2NzJHRXRKag==

Source :
https://animevy.com/nande-koko-ni-sensei-ga-subtitle-english-batch/

**Comment by timmyRS** [comment] 2019-11-25 02:41
Duplicate of #193

**Closed by timmyRS** 2019-11-25 02:41 UTC
