### ISSUE TITLE
plz bypass this annoying safelink if possible

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#372] opened 2019-08-22 12:12 UTC
safelink from sites: 
https://drivenime.com/boku-no-hero-academia-the-movie-futari-no-hero-sub-indonesia/
https://movieku.org/the-hobbit-3-subtitle-indonesia/
https://hananime.com/vinland-saga/

or add to crowd bypass if it's possible
thank you so much

**Comment by timmyRS** [comment] 2019-08-22 16:53
Duplicate of #193

**Closed by timmyRS** 2019-08-22 16:53 UTC
