### ISSUE TITLE
blogpedia.us safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#403] opened 2019-08-29 19:35 UTC
Example link :
http://blogpedia.us/?id=bVRsZW92VXhBUFdoaGYyclowRGtBbVhMSGpQcnY5My9hNHEwc2NYekdxaWhDeEt3OWIzaklMb2FBU1BXeXdmaQ==
http://blogpedia.us/?id=YUFFaWtYQjU4WlpRczNIWi9MbW9mbUlZNVRFVHRBMUFQd2pTWk9NYW41TWxhdVBqQmswMEpRTEhmWlJvUmQ0cA==

Source link : 
`https://pusatfilm21.com/aladdin-2019/`

**Comment by timmyRS** [comment] 2019-09-01 10:42
Duplicate of #193

**Closed by timmyRS** 2019-09-01 10:42 UTC
