### ISSUE TITLE
idntekno.me safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#497] opened 2019-10-06 09:59 UTC
Example link :
https://idntekno.me/?id=YmFVNVJ1bFdBZE9VYVhsbFhMNjYzWFBPajlqejY0T1pUUGtUNFRnYkcxQ3g3dVpCbmFsUDYzZ081eEliYjJScVRZL0NmVXcyV3ZBNVpVOThsZFB5d20zQ1EvUkVISElMUS9Uakx5VnFJUG89

https://idntekno.me/?id=YmFVNVJ1bFdBZE9VYVhsbFhMNjYzWFBPajlqejY0T1pUUGtUNFRnYkcxRDZBWWU2eXNYek04SWk2NU51OEFkd2RBb0hCVzJhYzJob1ZFSEQ0U3Y5TkdWUHN5QVllM3B6anluNWxXZ25MekE9

Source link : 
`https://kuramanime.com/black-fox/`

**Comment by timmyRS** [comment] 2019-10-06 22:21
Duplicate of #193

**Closed by timmyRS** 2019-10-06 22:21 UTC
