### ISSUE TITLE
request: lonelymoon.net

### ISSUE THREAD

**Issue by adammalyck** [timmyRS/Universal-Bypass#619] opened 2019-11-23 01:41 UTC
https://lonelymoon.net/?id=dC94MXMvbTRkK21jV1doNE1ZdWMzUUJza3FuSVFianU3aC85UHRrTUpJdz0=

**Comment by timmyRS** [comment] 2019-11-23 02:13
Duplicate of #193

**Closed by timmyRS** 2019-11-23 02:13 UTC

**Comment by adammalyck** [comment] 2019-11-23 02:52
is this will be fix in the next release?

**Comment by timmyRS** [comment] 2019-11-23 02:55
No.

**Comment by adammalyck** [comment] 2019-11-23 02:57
why?

**Comment by timmyRS** [comment] 2019-11-23 02:57
Because #193 has not been solved yet.

**Comment by adammalyck** [comment] 2019-11-23 02:59
oh, your mean this is still progress?\

sorry for my bad english

**Comment by timmyRS** [comment] 2019-11-23 03:00
Yes.

**Comment by adammalyck** [comment] 2019-11-23 03:01
ok, waiting for the next update

thanks for your hard working @timmyRS
