### ISSUE TITLE
Request refoblog.xyz

### ISSUE THREAD

**Issue by falfan2018** [timmyrs/Universal-Bypass#324] opened 2019-08-06 15:38 UTC
http://refoblog.xyz/?id=bkI1eDFFYkRwbFptYmxidEpmekpGbUZlMHlOdmZKcXhpbnFkVmovbmJUalE2OFlZMm5NeFVNUnZVWTJIZlRWV2k4RkFZUVU2RnZoMFloa3hPV3QwdlNCNVRiZFlSejVJd0ZHWElEQjNBMlRaN2p3WlVXdXlQUGpKY01Eazk2bzQ=

http://refoblog.xyz/?id=bkI1eDFFYkRwbFptYmxidEpmekpGalBMUHdNUWc4VktNN2l0cWkwUmJZOGtSUXBlS0NRZ3RPa2JhSWNoRkNaWG5QeVA2bnR0V1l6TkxyRFY3RjdqNGVrcWxLbE0xOVgwSjJFNDM3QVk5S2M9

http://refoblog.xyz/?id=bkI1eDFFYkRwbFptYmxidEpmekpGalBMUHdNUWc4VktNN2l0cWkwUmJZL3h6emVIWXJPeno2UUNwWjRmdzZWa2RSWHFOOXBhUFJPVm0wTGo0dTFxaW04cUxpelpNUFVYUVpkYW5Fby9YVXc9

**Comment by timmyrs** [comment] 2019-08-06 16:40
Duplicate of #193

**Closed by timmyrs** 2019-08-06 16:40 UTC
