### ISSUE TITLE
Plz support

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#353] opened 2019-08-16 13:17 UTC
1st Redirect `http://safe.doramaku.me/?web=aHR0cHM6Ly9raXNwcmF5LnhuZWV0LmlkLw==&targetlink=RUFicDhYSjMrQ255VUoxWjYwQ21Zc2N3VllpektkN3VCUE51WS9HN2NDMjJveHdZa2JmNjFOdTNLZlBBaXV6OWYwTUZhem1kbjk2S0lSZ21TSHhVQVVXQTFZVHV1WEx4THVHbi81RjBTQk09`
2nd Redirect `https://kispray.xneet.id/`
3rd Redirect `https://kispray.xneet.id/2019/07/10/the-best-7-foods-for-healthy-lungs-and-improved-breathing/`

source link `https://animebatchs.com/psycho-pass-bd-subtitle-indonesia-movie/`

**Comment by timmyRS** [comment] 2019-08-18 20:00
Duplicate of #193

**Closed by timmyRS** 2019-08-18 20:00 UTC

**Comment by anaklayangan** [comment] 2019-08-21 03:50
I think you missed something, this can be bypassed with a simple script
`document.querySelector('form').setAttribute('action','//'+location.hostname);
document.querySelector('input').setAttribute('name','link');`

**Comment by KagaKouko99** [comment] 2019-08-21 15:11
please support this annoying shortener to download movies
