### ISSUE TITLE
Request technlab.com

### ISSUE THREAD

**Issue by RaveN0X87** [timmyrs/Universal-Bypass#196] opened 2019-05-02 10:47 UTC
http://technlab.com/?id=b1A3MnFWOHI1eEZtT1U2L1NoaVJ5cGF2UWtlUUlHTjRhVnlucEtOT2hQYTNYOXcrY3FkNUllTk5WOEduUXNldld0Zm1nZjNvVUNJdnpyL09LRVpKcnRuc2ErdUxYQTZqMmMxU1lROTdHU2c9

**Comment by timmyrs** [comment] 2019-05-07 05:27
I'm not sure which cipher is used to encrypt the destination. However, that example link with the ciphertext of `b1A3MnFWOHI1eEZtT1U2L1NoaVJ5cGF2UWtlUUlHTjRhVnlucEtOT2hQYTNYOXcrY3FkNUllTk5WOEduUXNldld0Zm1nZjNvVUNJdnpyL09LRVpKcnRuc2ErdUxYQTZqMmMxU1lROTdHU2c9` leads to `https://drive.google.com/file/d/1VJqT-d5XcTNmc067zff911UXJdChu4Eh/view?usp=drive_web`

This could potentially be the same cipher as with #193

**Comment by timmyrs** [comment] 2019-06-03 08:46
Duplicate of #193.

**Closed by timmyrs** 2019-06-03 08:46 UTC
Labels: help wanted, new bypass
