### ISSUE TITLE
Request apasih.pw

### ISSUE THREAD

**Issue by RaveN0X87** [timmyrs/Universal-Bypass#230] opened 2019-05-16 05:03 UTC
http://apasih.pw/?id=a1NobVhjdlBzd2lucDN3OTN0V2l5dUJ5UlVaUzNFZ1V2Zk9NODNtS3JzSkNmaHVWUHY4TXRtQWZ5KzZLYTNDcUNma1BsbXpmelpxQXVrSmlMdEVCOGdXWEwwOTlHYVlRWWhMTk5WOVFWcUhtS0E1ekR3UXJKdFVLK1ZqditsNzI=
http://apasih.pw/?id=ZldGNnlMTElmUE90WEwrNC9OeFhLU1NqZVB1WjRRZUtZQlhPSC9lektkN2xkTVV3SVBCNmZrUlV1bXFHbGcvaXF2VEpZT1pvczdRcmt6bVFlcmF3TVE9PQ==
http://apasih.pw/?id=a1NobVhjdlBzd2lucDN3OTN0V2l5dUJ5UlVaUzNFZ1V2Zk9NODNtS3JzTFdQMklSY1A0bXpwdkdKZ1hzU2dNYndtOXVzeVhveEsrNGo1WHc3NkJiUEFBMXFLcmxwODVqYnFpN3JlZENoZk5kWllkUm9HNXZXVDhsMTRzNVAxOHQ=

`https://bakacan.id/one-piece-batch-episode-1-860-subtitle-indonesia/`

**Comment by timmyrs** [comment] 2019-05-16 10:12
I'm not sure which cipher is used to encode the destination in that `id` field. This could be related to #193 and #196.

**Comment by timmyrs** [comment] 2019-06-03 08:47
Duplicate of #193.

**Closed by timmyrs** 2019-06-03 08:47 UTC
Labels: help wanted, new bypass
