### ISSUE TITLE
situslangka.my.id safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#520] opened 2019-10-21 14:39 UTC
Example link :
https://situslangka.my.id/?id=OWRiUDBmUWFSY0JYaXl3eTl0SFEyRE5aTjZsT3lmT2hDQm9FZVZlUUF1QkVJSU5IYnVzTUYwVXR2UmIwajJ6SDIyWG8vVGhlWDBQa2xXZzVJMDhEd3c9PQ==

https://situslangka.my.id/?id=dkwySG9zbi9CTW1jSnFLcU9MZkFJVVJ6NlRxK1RlKzlIbHB3TlFOQktoazlqbWNDZnpXNkE1dTR6alFGb3pDQU85ZThRdzhkSVlrWmMvU2d1MTRSOUhZZGFBMFphckRwTlZ2UFVtYmNOM2M9

Source link : 
`https://quinimefansub.com/honkai-impact-3rd-bronya-subtitle-indonesia/`

**Comment by timmyRS** [comment] 2019-10-21 14:53
Duplicate of #193

**Closed by timmyRS** 2019-10-21 14:53 UTC
