### ISSUE TITLE
[Request] lonelymoon.net

### ISSUE THREAD

**Issue by falfan2018** [timmyrs/Universal-Bypass#220] opened 2019-05-13 16:37 UTC
Example link: 
https://lonelymoon.net/?id=dC94MXMvbTRkK21jV1doNE1ZdWMzWHdBK0xJNGhDWGZTbUZPYTdFOFRGUT0=
https://lonelymoon.net/?id=dC94MXMvbTRkK21jV1doNE1ZdWMzZmZJOXhtZGRjd2hNU0xIMUdSRHRpVT0=
https://lonelymoon.net/?id=dC94MXMvbTRkK21jV1doNE1ZdWMzUmFqRzhkZFlET2V0aEJCZFlBZ0RGaz0=

`https://pahe.in/game-of-thrones-season-8/`

**Comment by timmyrs** [comment] 2019-05-13 17:48
Duplicate of #193

**Closed by timmyrs** 2019-05-13 17:48 UTC
