### ISSUE TITLE
Request ceklinku.xyz

### ISSUE THREAD

**Issue by WaferNabati** [timmyRS/Universal-Bypass#464] opened 2019-09-20 05:01 UTC
https://ceklinku.xyz/?id=cThyWjJxYzhLSmFXMkhSYkVTaGdsMGFYV0NyTmphRFlPWXI1Y201V0YwNy9BWTdKSThxdUlFRW84V1lBdzNncUIzZUJXVHdNenJjZWZmSzZMRGltM3BiWkJTSkhyaXRhdjVOdHhmQTQvWkU9

https://ceklinku.xyz/?id=MmpZcVhabXdZUnAzZHE0WHhjYjdSNFpCc2puM0l2cG14NTQxb3BSWFVReTVtd2x6T1c4NUJCUGt5ckl1WG1ZYkFuSXhzdGN3VmxBLzdsWkFUS3pmNEE9PQ==

Source : 
`https://hinime.com/kanata-no-astra-sub-indo/`

**Comment by timmyRS** [comment] 2019-09-20 07:06
Duplicate of #193 

You should know this by now. Please just add a comment there.

**Closed by timmyRS** 2019-09-20 07:06 UTC

**Comment by WaferNabati** [comment] 2019-09-20 07:40
I can't distinguish which can or cannot be bypassed. like this case https://github.com/timmyRS/Universal-Bypass/issues/453

**Comment by timmyRS** [comment] 2019-09-20 08:37
In that case the "?r=aH" part made me know it's base64-encoded, specifically the "aH". When in doubt, just open an issue, not that it's a big deal.

**Comment by IllyaSan** [comment] 2019-09-20 14:01
aw, it interesting to do
