### ISSUE TITLE
vozdesportiva.com safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#394] opened 2019-08-28 17:06 UTC
Example link:
http://vozdesportiva.com/?id=c1FrTEVTaUtCTlRlczhXR3FQeHFNZDg2NXlENzA0cFR2N0JEYVBUNGJqRT0=
http://vozdesportiva.com/?id=c1FrTEVTaUtCTlRlczhXR3FQeHFNWHFhVHU5Z0pWSVA1V0dCRlZiUjVWaz0=

Source link:
`https://www.zenomovie.com/gekijouban-fate-stay-night-heavens-feel-ii-lost-butterfly-2019/`

**Comment by timmyRS** [comment] 2019-08-29 03:17
Duplicate of #193

**Closed by timmyRS** 2019-08-29 03:17 UTC
